### ISSUE TITLE
acf() got an unexpected keyword argument 'unbiased'

### ISSUE THREAD

**Issue by JackShDr** [blue-yonder/tsfresh#902]
**The problem**:  acf() got an unexpected keyword argument 'unbiased' when using the extract features function.

The error log is as follows:
"""
Traceback (most recent call last):
  File "/Applications/Anaconda3/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Applications/Anaconda3/anaconda3/envs/py38/lib/python3.8/site-packages/tsfresh/utilities/distribution.py", line 43, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "/Applications/Anaconda3/anaconda3/envs/py38/lib/python3.8/site-packages/tsfresh/utilities/distribution.py", line 42, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/Applications/Anaconda3/anaconda3/envs/py38/lib/python3.8/site-packages/tsfresh/feature_extraction/extraction.py", line 337, in _do_extraction_on_chunk
    return list(_f())
  File "/Applications/Anaconda3/anaconda3/envs/py38/lib/python3.8/site-packages/tsfresh/feature_extraction/extraction.py", line 317, in _f
    result = func(x, param=parameter_list)
  File "/Applications/Anaconda3/anaconda3/envs/py38/lib/python3.8/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 404, in agg_autocorrelation
    a = acf(x, unbiased=True, fft=n > THRESHOLD_TO_USE_FFT, nlags=max_maxlag)[1:]
TypeError: acf() got an unexpected keyword argument 'unbiased'
"""

**Anything else we need to know?**:

**Environment**:

- Python version: 3.8
- Operating System: MacOS
- tsfresh version: 0.18.0
- Install method (conda, pip, source): conda

**Comment by Naughty-Monkey** [comment]
I encountered the same issue today

**Comment by htrivino20** [comment]
> Temporarily reverting to statsmodel 0.12.1 fixes this
> 
> `pip install statsmodels==0.12.1`

Same issue on M1 using minoforge3 and it worked with statsmodels@0.12.1
